### ISSUE TITLE
Breaks on newer core.async version

### ISSUE THREAD

**Issue by akiroz** [jarohen/chime#15]
When my project depends on the latest version of core.async (currently 0.2.385) calling `chime-at` will result in the following exception:
```
Exception in thread "async-dispatch-4" java.lang.IllegalArgumentException: No implementation of method: :take! of protocol: #'clojure.core.async.impl.protocols/ReadPort found for class: chime$chime_ch$reify__19318
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:568)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:560)
	at clojure.core.async.impl.protocols$eval59$fn__60$G__50__67.invoke(protocols.clj:15)
	at clojure.core.async.impl.ioc_macros$take_BANG_.invokeStatic(ioc_macros.clj:1022)
	at clojure.core.async.impl.ioc_macros$take_BANG_.invoke(ioc_macros.clj:1021)
	at chime$chime_at$fn__19347$state_machine__5082__auto____19348$fn__19350.invoke(chime.clj:66)
	at chime$chime_at$fn__19347$state_machine__5082__auto____19348.invoke(chime.clj:65)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:1012)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:1011)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:1016)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:1014)
	at chime$chime_at$fn__19347.invoke(chime.clj:65)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```
Quick workaround: depend on 0.2.374

**Comment by jarohen** [comment]
Hi @akiroz, thanks for the report. I'm afraid I won't get chance to look at this before the weekend - have you got any idea about the cause?

Cheers,

James

**Comment by akiroz** [comment]
Hi jarohen,
Sorry but I haven't really had the time to look into this issue yet, I'll see what I can do after I get off work today.....

**Comment by akiroz** [comment]
@jarohen 
Alright, really sorry about this but it was a mistake on my part.
I couldn't reproduce the issue in a new project and in the end all I had to do was `lein clean` and it now works fine. (facepalm)
