### ISSUE TITLE
:error-handler does not seem to be called

### ISSUE THREAD

**Issue by tuscland** [jarohen/chime#22]
Hello,

Given this very simple test case:

```
(defn test-exception-with-handler []
  (chime-at (rest
    (periodic-seq (t/now)
                  (-> 5 t/seconds))
            (fn [time]
              (throw (Exception. "uh oh")))
            {:error-hander (fn [e]
                             (log/error e "something happened"))}))
```

It appears that the error handler is not called. Here's the printed output:
```
Exception in thread "async-thread-macro-11" java.lang.Error: java.lang.Exception: uh oh
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: uh oh
```

Am I missing something?
Thanks in advance!

**Comment by tuscland** [comment]
Please ignore, this was obviously my fault, there's a typo in my code (`:error-hander`). Sorry for the noise!

**Comment by jarohen** [comment]
No worries :)
