### ISSUE TITLE
Error running scheduled fn java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null

### ISSUE THREAD

**Issue by PlumpMath** [jarohen/chime#46]
3월 07, 2021 2:34:40 오전 chime.core invoke
경고: Error running scheduled fn
java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
	at java.base/java.io.StringReader.<init>(StringReader.java:50)
	at clojure.data.json$read_str.invokeStatic(json.clj:282)
	at clojure.data.json$read_str.doInvoke(json.clj:278)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at tray.pnix.route$jspSQ_loop.invokeStatic(route.clj:151)
	at tray.pnix.route$jspSQ_loop.invoke(route.clj:150)
	at tray.pnix.tray$START$fn__32985.invoke(tray.clj:52)
	at chime.core$chime_at$schedule_loop__27086$task__27090$fn__27091.invoke(core.clj:91)
	at chime.core$chime_at$schedule_loop__27086$task__27090.invoke(core.clj:90)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
}

**Comment by PlumpMath** [comment]
(chime/chime-at (-> (chime/periodic-seq (Instant/now) (Duration/ofSeconds 4)) rest)
                  (fn [time]
                    ;; -----------
                    (ROUTE/jspSQ-loop)  ;; <--- tray.clj:52
                
                    ;; -----------
                    ;; (Thread/sleep 750)
                    ))

**Comment by PlumpMath** [comment]
route.clj file

(defonce jspSQ (atom []))
(defn jspSQ-loop []
  (let [x (JSON/read-str  (:body  @(http-kit/get _jspSQ)) :key-fn keyword)]
    (if (= nil x)
      (reset! jspSQ [])
      (reset! jspSQ x))))

**Comment by jarohen** [comment]
Hi - this looks like an error in your scheduling fn?
